### PR TITLE
Fixed a visual bug with the plot component.

### PR DESCRIPTION
**Pull request by Trashtalk217**
Got a fix!

I haven't looked at the renderer codebase before this and I can't claim to understand it, but this fix does seem to work.

### CODE REVIEW

**Comment by Shinmera** [comment]
I think this method would fit better in the plot component definition file itself.

**Comment by Trashtalk217** [comment]
What is your opinion on the docstring? Should that be a comment instead?

**Comment by Shinmera** [comment]
Yes, though I don't think a comment is needed either, the code is self-explanatory enough.

**Comment by Trashtalk217** [comment]
Updated it to a comment. As someone trying to learn the codebase (and having not the easiest time), I think this'll help. This may just be a me-problem however.

**Comment by Shinmera** [comment]
Looking at the patch again, I don't think the `ensure-extent` is necessary. The `bounds` of a `layout-element` must always be an `extent` already anyway.

**Pull request merged**
